version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.8-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5440" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5440:5440"
    # Changing port to not interfere with other database
    command: -p 5440
