services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/ifeelgood-ui
    depends_on:
      db:
        condition: service_healthy
    command:
      - sh
      - -c
      - |
        rm -f tmp/pids/server.pid
        bundle install
        bundle exec rails db:create db:migrate
        bundle exec rails s -b '0.0.0.0'
  ui:
    build:
      dockerfile: Dockerfile
      target: npm-dev
      context: ./ifeelgood-ui
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./ifeelgood-ui:/app
    command: npm run dev -- --host
  db:
    image: postgres:14.8-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5440" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5440:5440"
    # Changing port to not interfere with other database
    command: -p 5440
