default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: ifeelgood_development
  port: 5440

test:
  <<: *development
  database: ifeelgood_test

production:
  <<: *default
  password: <%= ENV["IFEELGOOD_TEST_DATABASE_PASSWORD"] %>
